export const blogCategories: string[] = [
  'Travel',
  'Health and Wellness',
  'Lifestyle',
  'Science',
  'Business and Finance',
  'Food and Cooking',
  'Entertainment',
  'Education',
  'Sports',
];

export const blogTags = [
  'Tech Trends',
  'Travel Tips',
  'Fitness',
  'Fashion Trends',
  'Space Exploration',
  'Entrepreneurship',
  'Healthy Recipes',
  'Movie Reviews',
  'Educational Technology',
  'Soccer',
  'Programming Tips',
  'Adventure Travel',
  'Mental Health',
  'Beauty Tips',
  'Science News',
  'Investing Strategies',
  'Culinary Adventures',
  'Gaming News',
  'Study Tips',
  'Basketball',
  'Artificial Intelligence',
  'Home Decor Ideas',
  'Wellness Tips',
  'Relationship Advice',
  'Biology Discoveries',
  'Personal Finance',
  'Food Reviews',
  'TV Show Recommendations',
  'Career Development',
  'Football Analysis',
];

export const privileges = ['create', 'update', 'delete', 'read', 'any'];
